name: Test BlogTruyen View

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      COMPOSER_NO_DEV: 1
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 8.1
          extensions: curl

      - name: Exec script
        with:
          name: app
          run: |
            php text.php
